# ++++++++++++++++++++++++++++++++++++++++++++++++


services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword123
      MYSQL_DATABASE: wbl_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build: ./project-avatar-api
    container_name: backend_container
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:strongpassword123@mysql_container:3306/wbl_db
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build: ./project-avatar-ui
    container_name: frontend_container
    restart: always
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/admin
    ports:
      - "3000:3000"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
